// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr-O6TBdwT_IH4WfHYX05HJ00AvDB3VC8',
    appId: '1:1019823657147:web:cd003652c9de1441e1199e',
    messagingSenderId: '1019823657147',
    projectId: 'find-it-247007',
    authDomain: 'find-it-247007.firebaseapp.com',
    storageBucket: 'find-it-247007.appspot.com',
    measurementId: 'G-LEC3M43D33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhIrkQE5pYRrQswm24xUxZtIEtuIg8kcA',
    appId: '1:1019823657147:android:70b6d1352c5e3bc7e1199e',
    messagingSenderId: '1019823657147',
    projectId: 'find-it-247007',
    storageBucket: 'find-it-247007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZgR1dM6TRg0eCroZifMfiv126etHKZU',
    appId: '1:1019823657147:ios:44cb524f92c6ba72e1199e',
    messagingSenderId: '1019823657147',
    projectId: 'find-it-247007',
    storageBucket: 'find-it-247007.appspot.com',
    iosBundleId: 'com.example.dentsuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVZgR1dM6TRg0eCroZifMfiv126etHKZU',
    appId: '1:1019823657147:ios:ba034c3bfcc8d21ee1199e',
    messagingSenderId: '1019823657147',
    projectId: 'find-it-247007',
    storageBucket: 'find-it-247007.appspot.com',
    iosBundleId: 'com.example.dentsuApp.RunnerTests',
  );
}
